stages:
  - lint
  - build

Format terraform code:
  stage: lint
  image: alpine
  needs: []
  before_script:
    - apk add terraform
  script:
    - terraform fmt -check

Format go code:
  stage: lint
  image: alpine
  needs: []
  before_script:
    - apk add go
  script:
    - test -z "$(go fmt)"

Build:
  stage: build
  image: alpine
  needs: []
  before_script:
    - apk add go make
  script:
    - make terraform-provider-configupdater
