stages:
  - sync
  - lint
  - build
  - release


# Conditions
#############
.if-default-branch-refs: &if-default-branch-refs
  if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

.if-tag: &if-tag
  if: '$CI_COMMIT_TAG'

.if-merge-request: &if-merge-request
  if: '$CI_MERGE_REQUEST_IID'


# Workflow
###########
workflow:
  rules:
    - <<: *if-tag
    - <<: *if-default-branch-refs
    - <<: *if-merge-request


include:
  - project: labs/salt-automation
    file:
      - gitlab-ci-templates/common/no-interrupt.v1.yml
      - gitlab-ci-templates/common/conventional-commits.v1.yml


Format terraform code:
  stage: lint
  image: alpine
  needs: []
  before_script:
    - apk add terraform
  script:
    - terraform fmt -check


Format go code:
  stage: lint
  image: alpine
  needs: []
  before_script:
    - apk add go
  script:
    - test -z "$(go fmt)"


Build:
  stage: build
  image: alpine
  needs: []
  before_script:
    - apk add go make
  script:
    - make terraform-provider-configupdater
