branches:
  - master
tagFormat: "${version}"
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "@semantic-release/gitlab"
    - assets:
        - path: CHANGELOG.md
          label: Changelog
